/**
 * Jharkhand 24 Districts Master Registry
 * Optimized for Programmatic Geo-Silo SEO & Entity Search
 */

export interface DistrictInfo {
  slug: string;
  name: string;
  hindiName: string;
  headquarters: string;
  division: string;
  populationEstimate: string;
  knownFor: string;
  keywords: string[];
  lat: number;
  lng: number;
}

export const JHARKHAND_DISTRICTS: DistrictInfo[] = [
  {
    slug: 'ranchi',
    name: 'Ranchi',
    hindiName: 'राँची',
    headquarters: 'Ranchi',
    division: 'South Chotanagpur',
    populationEstimate: '2.9 Million',
    knownFor: 'State Capital, JSCA Stadium, Hundru Falls, Heavy Engineering Corporation (HEC)',
    keywords: ['Ranchi breaking news', 'Ranchi crime updates', 'Ranchi municipal corporation', 'RIMS Ranchi updates', 'Jharkhand High Court decisions'],
    lat: 23.3441,
    lng: 85.3096,
  },
  {
    slug: 'dhanbad',
    name: 'Dhanbad',
    hindiName: 'धनबाद',
    headquarters: 'Dhanbad',
    division: 'North Chotanagpur',
    populationEstimate: '2.7 Million',
    knownFor: 'Coal Capital of India, IIT (ISM) Dhanbad, BCCL, Coal mining belt',
    keywords: ['Dhanbad coal news', 'BCCL updates', 'Dhanbad railway division', 'Dhanbad crime news', 'Jharia fire underground updates'],
    lat: 23.7957,
    lng: 86.4304,
  },
  {
    slug: 'east-singhbhum',
    name: 'East Singhbhum (Jamshedpur)',
    hindiName: 'पूर्वी सिंहभूम (जमशेदपुर)',
    headquarters: 'Jamshedpur',
    division: 'Kolhan',
    populationEstimate: '2.3 Million',
    knownFor: 'Steel City, Tata Steel, XLRI, Dalma Wildlife Sanctuary, Industrial Hub',
    keywords: ['Jamshedpur news', 'Tata Steel updates', 'Tatanagar station news', 'Kadma Sakchi Bistupur news', 'Kolhan university updates'],
    lat: 22.8046,
    lng: 86.2029,
  },
  {
    slug: 'bokaro',
    name: 'Bokaro',
    hindiName: 'बोकारो',
    headquarters: 'Bokaro Steel City',
    division: 'North Chotanagpur',
    populationEstimate: '2.1 Million',
    knownFor: 'Steel Authority of India (SAIL), Bokaro Thermal Power, Education City',
    keywords: ['Bokaro Steel City news', 'BSL updates', 'Chas Bokaro news', 'Bermo coalfield news', 'Bokaro industrial belt'],
    lat: 23.6693,
    lng: 86.1511,
  },
  {
    slug: 'deoghar',
    name: 'Deoghar',
    hindiName: 'देवघर',
    headquarters: 'Deoghar',
    division: 'Santhal Pargana',
    populationEstimate: '1.5 Million',
    knownFor: 'Baba Baidyanath Dham (Jyotirlinga), AIIMS Deoghar, Shravani Mela, Spiritual Capital',
    keywords: ['Deoghar Baidyanath Dham news', 'AIIMS Deoghar updates', 'Deoghar airport flights', 'Shravani Mela live updates', 'Jasidih junction news'],
    lat: 24.4826,
    lng: 86.7000,
  },
  {
    slug: 'hazaribagh',
    name: 'Hazaribagh',
    hindiName: 'हज़ारीबाग़',
    headquarters: 'Hazaribagh',
    division: 'North Chotanagpur',
    populationEstimate: '1.7 Million',
    knownFor: 'Hazaribagh National Park, Vinoba Bhave University, Canary Hill, Coal Mining',
    keywords: ['Hazaribagh news', 'Vinoba Bhave University results', 'Barkagaon mining updates', 'Hazaribagh sadar hospital', 'Hazaribagh administration'],
    lat: 23.9925,
    lng: 85.3637,
  },
  {
    slug: 'giridih',
    name: 'Giridih',
    hindiName: 'गिरिडीह',
    headquarters: 'Giridih',
    division: 'North Chotanagpur',
    populationEstimate: '2.4 Million',
    knownFor: 'Parasnath Hill (Shikharji Jain pilgrimage), Mica and Coal fields, Usri Falls',
    keywords: ['Giridih news', 'Parasnath Shikharji updates', 'Giridih district administration', 'Dumri Bermo Giridih news'],
    lat: 24.1856,
    lng: 86.3056,
  },
  {
    slug: 'ramgarh',
    name: 'Ramgarh',
    hindiName: 'रामगढ़',
    headquarters: 'Ramgarh Cantonment',
    division: 'South Chotanagpur',
    populationEstimate: '950,000',
    knownFor: 'Rajrappa Chhinnamasta Temple, Sikh Regimental Centre, Patratu Valley & Dam',
    keywords: ['Ramgarh news', 'Patratu valley tourism', 'Rajrappa mandir updates', 'Ramgarh cantonment news', 'Patratu thermal power plant'],
    lat: 23.6300,
    lng: 85.5100,
  },
  {
    slug: 'palamu',
    name: 'Palamu',
    hindiName: 'पलामू',
    headquarters: 'Medininagar (Daltonganj)',
    division: 'Palamu',
    populationEstimate: '1.9 Million',
    knownFor: 'Betla National Park, Palamu Fort, Historic Daltonganj, North Koel River',
    keywords: ['Palamu news', 'Medininagar Daltonganj news', 'Palamu police administration', 'Betla park tourism', 'Nilamber Pitamber university'],
    lat: 24.0430,
    lng: 84.0722,
  },
  {
    slug: 'dumka',
    name: 'Dumka',
    hindiName: 'दुमका',
    headquarters: 'Dumka',
    division: 'Santhal Pargana',
    populationEstimate: '1.3 Million',
    knownFor: 'Sub-capital of Jharkhand, Basukinath Temple, Massanjore Dam, Sido Kanhu Murmu University',
    keywords: ['Dumka sub capital news', 'Basukinath temple news', 'Massanjore dam updates', 'SKMU Dumka results', 'Dumka district collectorate'],
    lat: 24.2676,
    lng: 87.2486,
  },
  {
    slug: 'godda',
    name: 'Godda',
    hindiName: 'गोड्डा',
    headquarters: 'Godda',
    division: 'Santhal Pargana',
    populationEstimate: '1.3 Million',
    knownFor: 'Adani Ultra Supercritical Thermal Power Plant, Lalmatia Coal Mines (ECL), Maa Yogini Temple',
    keywords: ['Godda news', 'Adani power plant Godda updates', 'Lalmatia ECL coal mining', 'Godda railway line', 'Patan Devi Godda'],
    lat: 24.8267,
    lng: 87.2144,
  },
  {
    slug: 'garhwa',
    name: 'Garhwa',
    hindiName: 'गढ़वा',
    headquarters: 'Garhwa',
    division: 'Palamu',
    populationEstimate: '1.3 Million',
    knownFor: 'Border with UP, Bihar & Chhattisgarh, Sukhaldari Falls, Radha Krishna Temple Nagar Untari',
    keywords: ['Garhwa news', 'Nagar Untari Banshidhar temple', 'Garhwa administration news', 'Ranka Garhwa road updates'],
    lat: 24.1600,
    lng: 83.8100,
  },
  {
    slug: 'latehar',
    name: 'Latehar',
    hindiName: 'लातेहार',
    headquarters: 'Latehar',
    division: 'Palamu',
    populationEstimate: '730,000',
    knownFor: 'Netarhat (Queen of Chotanagpur), Lodh Falls, Magnolia Sunset Point, Forest reserves',
    keywords: ['Latehar news', 'Netarhat tourism news', 'Lodh falls Latehar', 'Mahuadanr wolf sanctuary', 'Latehar district news'],
    lat: 23.7431,
    lng: 84.5024,
  },
  {
    slug: 'chatra',
    name: 'Chatra',
    hindiName: 'चतरा',
    headquarters: 'Chatra',
    division: 'North Chotanagpur',
    populationEstimate: '1.0 Million',
    knownFor: 'Maa Bhadrakali Temple Itkhori, Tamasin Falls, Gateway of Jharkhand, Coal projects',
    keywords: ['Chatra news', 'Itkhori Bhadrakali temple', 'North Karanpura NTPC Tandwa', 'Chatra police news'],
    lat: 24.2092,
    lng: 84.8719,
  },
  {
    slug: 'koderma',
    name: 'Koderma',
    hindiName: 'कोडरमा',
    headquarters: 'Koderma (Jhumri Telaiya)',
    division: 'North Chotanagpur',
    populationEstimate: '720,000',
    knownFor: 'Mica Capital of the World, Jhumri Telaiya, Tilaiya Dam, Koderma Wildlife Sanctuary',
    keywords: ['Koderma news', 'Jhumri Telaiya news', 'Tilaiya dam tourism', 'Koderma railway junction news'],
    lat: 24.4673,
    lng: 85.5940,
  },
  {
    slug: 'jamtara',
    name: 'Jamtara',
    hindiName: 'जामताड़ा',
    headquarters: 'Jamtara',
    division: 'Santhal Pargana',
    populationEstimate: '790,000',
    knownFor: 'Cyber intelligence and policing reforms, Ishwar Chandra Vidyasagar Karma Bhumi Karmatanr',
    keywords: ['Jamtara news', 'Jamtara cyber crime police updates', 'Karmatanr Vidyasagar news', 'Mihijam Jamtara updates'],
    lat: 23.9632,
    lng: 86.8024,
  },
  {
    slug: 'sahibganj',
    name: 'Sahibganj',
    hindiName: 'साहिबगंज',
    headquarters: 'Sahibganj',
    division: 'Santhal Pargana',
    populationEstimate: '1.1 Million',
    knownFor: 'Only district in Jharkhand touched by River Ganga, Multi-modal cargo terminal, Rajmahal Fossil Park',
    keywords: ['Sahibganj Ganga port news', 'Rajmahal hills fossils', 'Sahibganj stone mining', 'Udhwa bird sanctuary'],
    lat: 25.2425,
    lng: 87.6447,
  },
  {
    slug: 'pakur',
    name: 'Pakur',
    hindiName: 'पाकुड़',
    headquarters: 'Pakur',
    division: 'Santhal Pargana',
    populationEstimate: '900,000',
    knownFor: 'Black stone crushing industry, Santhal tribal heritage, Martello Tower, Bordering West Bengal',
    keywords: ['Pakur news', 'Pakur stone chips mining', 'Littipara Pakur updates', 'Pakur administration'],
    lat: 24.6333,
    lng: 87.8500,
  },
  {
    slug: 'lohardaga',
    name: 'Lohardaga',
    hindiName: 'लोहरदगा',
    headquarters: 'Lohardaga',
    division: 'South Chotanagpur',
    populationEstimate: '460,000',
    knownFor: 'Bauxite Mines, Hindalco smelting supply, Prachin Shiv Mandir Kisko',
    keywords: ['Lohardaga news', 'Lohardaga bauxite mining', 'Bagru hills Hindalco', 'Kisko Lohardaga news'],
    lat: 23.4300,
    lng: 84.6800,
  },
  {
    slug: 'gumla',
    name: 'Gumla',
    hindiName: 'गुमला',
    headquarters: 'Gumla',
    division: 'South Chotanagpur',
    populationEstimate: '1.0 Million',
    knownFor: 'Birthplace of Lord Hanuman (Anjan Dham), Tanginath Dham, Birsa Munda movement roots',
    keywords: ['Gumla news', 'Anjan Dham Gumla', 'Tanginath temple news', 'Basia Sisai Gumla updates'],
    lat: 23.0428,
    lng: 84.5422,
  },
  {
    slug: 'khunti',
    name: 'Khunti',
    hindiName: 'खूँटी',
    headquarters: 'Khunti',
    division: 'South Chotanagpur',
    populationEstimate: '530,000',
    knownFor: 'Birthplace of Bhagwan Birsa Munda (Ulihatu), Lac production hub, Panchghagh Falls',
    keywords: ['Khunti news', 'Birsa Munda Ulihatu', 'Panchghagh falls Khunti', 'Khunti administration updates'],
    lat: 23.0733,
    lng: 85.2789,
  },
  {
    slug: 'simdega',
    name: 'Simdega',
    hindiName: 'सिमडेगा',
    headquarters: 'Simdega',
    division: 'South Chotanagpur',
    populationEstimate: '600,000',
    knownFor: 'Cradle of Indian Hockey (Salima Tete, Nikki Pradhan), Kelaghagh Dam, Tribal sports culture',
    keywords: ['Simdega news', 'Simdega hockey updates', 'Kelaghagh dam tourism', 'Kolebira Simdega news'],
    lat: 22.6167,
    lng: 84.5000,
  },
  {
    slug: 'west-singhbhum',
    name: 'West Singhbhum (Chaibasa)',
    hindiName: 'पश्चिमी सिंहभूम (चाईबासा)',
    headquarters: 'Chaibasa',
    division: 'Kolhan',
    populationEstimate: '1.5 Million',
    knownFor: 'Largest district by area, Saranda Forest (Seven Hundred Hills), Iron ore mines (Noamundi, Kiriburu)',
    keywords: ['Chaibasa news', 'Saranda forest news', 'Noamundi iron ore mining', 'West Singhbhum administration'],
    lat: 22.5500,
    lng: 85.8000,
  },
  {
    slug: 'saraikela-kharsawan',
    name: 'Saraikela Kharsawan',
    hindiName: 'सरायकेला खरसावां',
    headquarters: 'Saraikela',
    division: 'Kolhan',
    populationEstimate: '1.1 Million',
    knownFor: 'Chhau Dance (UNESCO Intangible Cultural Heritage), Adityapur Industrial Area (Asia’s largest SME hub)',
    keywords: ['Saraikela news', 'Adityapur industrial area news', 'Chhau dance Saraikela', 'Chandil dam tourism'],
    lat: 22.7000,
    lng: 85.9300,
  },
];

export function getDistrictBySlug(slug: string): DistrictInfo | undefined {
  const clean = slug.toLowerCase().trim();
  return JHARKHAND_DISTRICTS.find(d => 
    d.slug === clean || 
    d.name.toLowerCase().includes(clean) ||
    clean.includes(d.slug)
  );
}
